### PR TITLE
create a new notebook check author

### PR DESCRIPTION
**Pull request by Panmax**

### CODE REVIEW

**Comment by levlaz** [comment]
Can we flash a message if the notebook already exists to let the user know why they cannot add a new notebook?

**Comment by Panmax** [comment]
@levlaz ok, i'll do it  : )

**Comment by Panmax** [comment]
@levlaz error message has wrote in else bolck

``` python
        if Notebook.query.filter_by(
                title=form.title.data, 
                author_id=current_user.id).first() == None:
            notebook = Notebook(
                title=form.title.data,
                author_id=current_user.id)
            db.session.add(notebook)
            db.session.commit()
        else:
            flash('A notebook with name {0} already exists.'.format(form.title.data))
```

**Comment by levlaz** [comment]
@Panmax this looks great but did you commit and push it? I don't see the update in the PR.

**Comment by Panmax** [comment]
you need to expand code and you will see it

**Pull request merged**
