### PR TITLE
added tooltip to note

### PR DESCRIPTION
**Pull request by makalaaneesh**
Added the respective tooltips to the action icons.

### CODE REVIEW

**Comment by levlaz** [comment]
@makalaaneesh thank you very much! A couple of things. 
1. Can you write favorite instead of favourite? :) 
2. Do you have a screenshot of this? I want to see where the tool tips show up and what they look like.

**Comment by makalaaneesh** [comment]
screenshot from 2015-12-15 22 24 10

This is how it looks! Require any changes?
And sure, i'll change the spelling right away :)

**Comment by levlaz** [comment]
@makalaaneesh can we have this show up below instead? you can add `data-placement="bottom"` to the markup. 

Reference: http://getbootstrap.com/javascript/#static-tooltip

**Comment by makalaaneesh** [comment]
@levlaz Done :)

**Comment by makalaaneesh** [comment]
screenshot from 2015-12-15 22 39 47

**Comment by levlaz** [comment]
@makalaaneesh This is perfect, thank you so much!

**Comment by makalaaneesh** [comment]
:+1:

**Pull request merged**
