### PR TITLE
Deleted note is listed in tag page

### PR DESCRIPTION
**Pull request by Frederick-S**
If we visit the tag page, it lists all notes by that tag, including the deleted notes.

### CODE REVIEW

**Comment by levlaz** [comment]
@Frederick-S could we handle this in the query instead?

**Comment by Frederick-S** [comment]
@levlaz Do you mean `Note.query.filter_by`?

**Comment by levlaz** [comment]
@Frederick-S that is right, just do `filter_by(is_deleted=False)` (and whatever other parameters we need)

**Comment by Frederick-S** [comment]
@levlaz I am a little confused. The `_show_notes` method in `Notebook` model doesn't use query. Do you want to rewrite `_get_notes` method? Like:

``` py
def _get_notes(self):
    return Note.query.filter_by(...)
```

**Comment by levlaz** [comment]
@Frederick-S Sorry I confused myself :( 

This is perfect as is, thanks!

**Pull request merged**
