### PR TITLE
Add default user admin to try braindump after install

### PR DESCRIPTION
**Pull request by jo541**

### CODE REVIEW

**Comment by levlaz** [comment]
Thanks for this! 

I wonder if it would be better to have a first run script that creates a new user instead of hardcoding it in the code. In the future there will be some functionality that admins have that regular users do not, and from a security perspective if everyone knew that the admin password was 'admin' then self-hosted installations would be vulnerable. 

What do you think?

**Comment by levlaz** [comment]
[This issue](https://github.com/levlaz/braindump/issues/25) calls for creating a new user in dev mode, so this would be fine if we added: 

```
if app.config['DEBUG'] == True:
```

Then this code would only run during development mode and not in a production environment.

**Comment by jo541** [comment]
No problem, I realy think your project it's interesting.

I think,there are two possibilty to create admin user,Or you add on
configuration file a line to specified the name and passowrd user or your
hardcoding the admin with default password and user name . I work lot of
time on Odoo (it's an ERP) and the admin user is create when the first time
you launch server . with befault password admin and user , after you can
change the password and name.

I want to help you to improved your "dumpbrain", if you want ^^ .

2015-12-12 2:23 GMT+01:00 Lev Lazinskiy notifications@github.com:

**Comment by levlaz** [comment]
@jo541 Can you add the bit I put in to your PR, I will still like to merge this for dev mode :)

**Comment by jo541** [comment]
It's okey ! :D

2015-12-14 22:53 GMT+01:00 Lev Lazinskiy notifications@github.com:

**Comment by levlaz** [comment]
@jo541 This is perfect, thank you so much!

**Pull request merged**
