### PR TITLE
In reference to #156 . Added a TODO view

### PR DESCRIPTION
**Pull request by makalaaneesh**
bd

@levlaz What do you think?

### CODE REVIEW

**Comment by levlaz** [comment]
I was thinking it should look more like this: 

todo

**Comment by makalaaneesh** [comment]
@levlaz Alright! Will work on it. Do you want the user to be able to check the TODO item off from within this view or not?

**Comment by levlaz** [comment]
Yes for sure -- sorry just made a quick mock up. 

It would also be cool to be able to sort by Notebook and Dates  -- but this can come later. :)

**Comment by makalaaneesh** [comment]
Cool! One question though. How do i link to the note? `BASE_URL/#note_id` doesn't seem to work.

**Comment by levlaz** [comment]
It should just be something like this: 

```
<a href="{{ url_for('.note', id=note.id) }}"><h5>{{ note.title | truncate(100) }}</h5></a>
```

**Comment by makalaaneesh** [comment]
Oh cool. Didn't know you could write it that way :)

**Comment by levlaz** [comment]
Yeah `url_for` is magical :)

**Comment by levlaz** [comment]
Im gonna cut a release when this is done. :D Let me know if you need any help.

**Comment by makalaaneesh** [comment]
bd

This is how it looks now :)

**Comment by levlaz** [comment]
Oh wow this is beautiful. :) 

Thanks so much! 

Are you more or less done? Lets go ahead and ship this. 

Best, 
Lev

**Comment by makalaaneesh** [comment]
@levlaz Yup! Done now :)

**Comment by levlaz** [comment]
Can you do me a favor and paste the output of `python manage.py test` here? 

CI is great -- but since I am doing a deployment I cannot enable permissive builds which is required in order to store all of the ENVARS. Otherwise anyone will have access to all of the keys :(

**Comment by makalaaneesh** [comment]
Ah, I see! I will paste in a minute. I am getting a lot of errors pertaining to 

``` python
OperationalError: (psycopg2.OperationalError) fe_sendauth: no password supplied
```

**Comment by makalaaneesh** [comment]
@levlaz There are conflicts because of the testing config. I tried to use the development config, but that's introducing different kind of errors!

This is the output after putting in the correct credentials.

``` python
(dev-brain)makala@aneesh:~/test/braindump$ python manage.py test
/home/makala/test/dev-brain/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')

Running tests...
----------------------------------------------------------------------
..............E...E
======================================================================
ERROR [0.035s]: test_password_reset (test_user_model.UserModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/makala/test/braindump/tests/test_user_model.py", line 35, in test_password_reset
    u.reset_password(reset_token, 'new_password')
  File "/home/makala/test/braindump/app/models.py", line 116, in reset_password
    db.session.commit()
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2015, in flush
    self._flush(objects)
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2133, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2097, in _flush
    flush_context.execute()
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 785, in _emit_insert_statements
    execute(statement, params)
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) relation "users" does not exist
LINE 1: INSERT INTO users (email, username, password_hash, confirmed...
                    ^
 [SQL: 'INSERT INTO users (email, username, password_hash, confirmed, avatar_hash, created_date, updated_date) VALUES (%(email)s, %(username)s, %(password_hash)s, %(confirmed)s, %(avatar_hash)s, %(created_date)s, %(updated_date)s) RETURNING users.id'] [parameters: {'updated_date': datetime.datetime(2016, 1, 11, 20, 29, 4, 740947), 'username': None, 'confirmed': False, 'created_date': datetime.datetime(2016, 1, 11, 20, 29, 4, 740937), 'avatar_hash': None, 'email': None, 'password_hash': 'pbkdf2:sha512:1000$PA2ZiP0N$bc52111b11fbb0e3d3919116b2b076613c4d6b673d83a6340368992f13e9a0f46064824e5fbd119ff111b4bc0e492db2f13ed3a75d8a798840c1fd5da16c651b'}]

======================================================================
ERROR [0.016s]: test_user_confirmation (test_user_model.UserModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/makala/test/braindump/tests/test_user_model.py", line 28, in test_user_confirmation
    u.confirm(confirmation_token)
  File "/home/makala/test/braindump/app/models.py", line 153, in confirm
    db.session.commit()
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 390, in commit
    self._assert_active(prepared_ok=True)
  File "/home/makala/test/dev-brain/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) relation "users" does not exist
LINE 1: INSERT INTO users (email, username, password_hash, confirmed...
                    ^
 [SQL: 'INSERT INTO users (email, username, password_hash, confirmed, avatar_hash, created_date, updated_date) VALUES (%(email)s, %(username)s, %(password_hash)s, %(confirmed)s, %(avatar_hash)s, %(created_date)s, %(updated_date)s) RETURNING users.id'] [parameters: {'updated_date': datetime.datetime(2016, 1, 11, 20, 29, 4, 740947), 'username': None, 'confirmed': False, 'created_date': datetime.datetime(2016, 1, 11, 20, 29, 4, 740937), 'avatar_hash': None, 'email': None, 'password_hash': 'pbkdf2:sha512:1000$PA2ZiP0N$bc52111b11fbb0e3d3919116b2b076613c4d6b673d83a6340368992f13e9a0f46064824e5fbd119ff111b4bc0e492db2f13ed3a75d8a798840c1fd5da16c651b'}]

----------------------------------------------------------------------
Ran 19 tests in 15.386s

FAILED (errors=2)

Generating XML reports...
```

I'm not really sure what to do!

**Comment by levlaz** [comment]
In the testing config a new DB should be created each time. I will look into this too -- in the meantime those tests that failed are fine for this specific purpose. Thanks again!

**Pull request merged**
