### PR TITLE
Added respective notebook title to each note

### PR DESCRIPTION
**Pull request by srisankethu**
@levlaz right! it just went out of my mind

### CODE REVIEW

**Comment by levlaz** [comment]
I am not sure if this is necessary TBH. 

1) If you click on a specific notebook it only shows you those notes now 
2) The notebook is shown as a label under the note that you are currently looking at

**Comment by srisankethu** [comment]
@levlaz The label is shown only when the note is opened.But if the user just wants to glance through the list of notes , he can get to see to which notebook does a book belong.
By the way,UI is broken.

**Comment by srisankethu** [comment]
@levlaz Mobile UI is completely broken

**Comment by levlaz** [comment]
Have you been using the app on mobile??? It has been completely broken since the beginning.

**Comment by srisankethu** [comment]
Yaa n now completely

**Pull request closed without merging**
