### PR TITLE
Added note count to notebook

### PR DESCRIPTION
**Pull request by srisankethu**
Is this OKkk? because a db query will perform a similar function like notebook._count_note...something

### CODE REVIEW

**Comment by levlaz** [comment]
There is a better way, there is no loop required because the reference to the notes model already exists. Querying the DB is an O(1) operation compared to a O(N) for loop :)

**Comment by srisankethu** [comment]
I thought that the Db command internally goes through the iteration or else how could it access every input in the Db.so thought it would be O(n)

**Comment by levlaz** [comment]
No, this is not correct. When a relationship exists between two tables and you want to count the amount of records in a related table the DB performs a JOIN which is not O(n) there is no iteration occurring because it is a single query. No matter how many associated records there are, it will always be a single query. Granted, joins can get very expensive as well, but in this case a single join is much more efficient than iterating through multiple records in python. 

So in this case, if we just want to get a count of all of the records that are attached to a single note we can do: 

```
length = Note.query.filter_by(notebook_id=notebook.id).count()
```

To show how many note records are attached to a particular Notebook.

**Comment by srisankethu** [comment]
@levlaz Thanks,I just thought a query's runtime depends on the number of records i.e if n records it is O(n).I will change it!

**Comment by levlaz** [comment]
Nope, thats the magic of databases :) 

This is why you should always run a query if you can. I see a lot of people who try to rewrite basic DB functions in their code. Its a poor habit.

**Pull request closed without merging**
