### PR TITLE
In reference to issue #115

### PR DESCRIPTION
**Pull request by srisankethu**
I guess these changes seem better
1. A confirmed user cannot access auth/confirm
2.A logged in user cannot access auth/login

### CODE REVIEW

**Comment by srisankethu** [comment]
@levlaz Please review this and share your opinion

**Comment by levlaz** [comment]
@srisankethu sorry for the delay, I am gonna pull this down and test it :) Thank you for your contribution!

**Comment by levlaz** [comment]
Perfect, works great!

**Comment by levlaz** [comment]
No i lied :( it only works if you are signed in.. still broken in prod and throwing 500 This is because an anonymous user does not have the property of confirmed.

**Pull request merged**
